[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "fixtranslator"
description = "FIX protocol translator — parse FIX logs to human-readable JSON and forward to logging platforms."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "Apache-2.0" }
authors = [
  { name="Franco Manna", email="manna.franco@gmail.com" }
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11"
]
keywords = ["fix", "financial", "parser", "splunk", "datadog"]
dynamic =["version"]

[project.urls]
"Homepage" = "https://github.com/Terrenus/FIXTranslator"
"Repository" = "https://github.com/Terrenus/FIXTranslator"

[tool.setuptools.packages.find]
where = ["."]
include = ["fixparser*"]

[tool.setuptools_scm]
write_to = "fixparser/_version.py"
local_scheme = "node-and-date"