name: CI

# Run on pushes & PRs to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Required permissions for this workflow (CodeQL needs security-events)
permissions:
  contents: read
  security-events: write

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensure setuptools_scm and other jobs can access tags/history

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # dev tools
          pip install ruff pytest bandit setuptools_scm

      - name: Lint (ruff)
        run: |
          # run ruff in check mode in CI (no --fix)
          ruff check .

      - name: Run tests
        run: |
          pytest -q

      - name: Security scan (Bandit)
        run: |
          bandit -r fixparser -ll || true

  build-dist:
    name: Build distribution (wheel/sdist)
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout repository (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # critical for setuptools_scm to read tags/version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          pip install build setuptools_scm

      - name: Build wheel and sdist
        run: |
          python -m build

      - name: Verify version
        run: |
          python -c "import fixparser; print('package version:', getattr(fixparser,'__version__','(none)'))"

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout repository (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild (if applicable)
        uses: github/codeql-action/autobuild@v3
        # If autobuild doesn't find the build, consider adding explicit build commands here

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3