name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (dev tools)
        run: |
          python -m pip install --upgrade pip
          # install runtime deps from requirements.txt if present
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # install dev/test tools
          pip install ruff pytest bandit setuptools_scm

      - name: Install package (editable)
        run: |
          # editable install so test imports will work and setuptools_scm is available
          pip install -e .

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Run tests
        run: |
          pytest -q

      - name: Security scan (Bandit)
        run: |
          bandit -r fixparser -ll || true

  build-dist:
    name: Build distribution (wheel/sdist)
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout repository (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools_scm

      - name: Build wheel and sdist
        run: |
          python -m build

      - name: Verify version
        run: |
          python -c "import fixparser; print('package version:', getattr(fixparser,'__version__','(none)'))"

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout repository (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild (if applicable)
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3